#!/bin/bash
#
# sudo install-core
#
# This function installs the core Ubuntu packages according to the list in
# the file
#
#    core-packages.list
#
# For each line in that file, it checks if the package is installed before
# attempting to install it.
#

# Versions:
#  2013-07-06 @dalle   : First version

# Get the packages from the list.
packagesCore=$( awk '$1 ~ /^[a-z0-9]/ { print $1 }' packages.list )

# Loop through them.
for package in $packagesCore; do
	# Echo it.
	echo "Checking package: $package"
	# Check the current status.
	packageStatus=$( dpkg --get-selections | grep -P "^$package\t" | awk '{print $2}' )
	# Process the status.
	if [ "$packageStatus" == "install" ]; then
		echo "Package currently installed."
	elif [ "$packageStatus" == "deinstall" ]; then
		echo "Package marked for deinstallation; attempting to (re)install."
		apt-get install $package
	else
		echo "Installing."
		apt-get install $package
	fi
done

# Copy all of the files in the bin folder to /usr/local/bin
for f in $( ls bin/ ); do
	# Print label.
	echo "Copying script '$f' to local directory"
	# Check if such a file already exists.
	if [[ -f "/usr/local/bin/$f" ]]; then
		echo "Warning: overwriting /usr/local/bin/$f"
	fi
	# Copy the file.
	cp -f bin/$f /usr/local/bin/
done

# Restart the OpenAFS kernel
/etc/init.d/openafs-client restart
