#!/bin/bash
#
# sudo install-core
#
# This function installs the core Ubuntu packages according to the list in
# the file
#
#    core-packages.list
#
# For each line in that file, it checks if the package is installed before
# attempting to install it.
#

# Versions:
#  2013-07-06 @dalle   : First version

# Get the packages from the list.
# Ignore comments and empty lines.
packagesCore=$( awk '$1 ~ /^[a-z0-9]/ { print $1 }' packages.list )

# Loop through them.
for package in $packagesCore; do
	# Echo it.
	echo "Checking package: $package"
	# Check the current status.
	packageStatus=$( dpkg --get-selections | grep -P "^$package\t" | awk '{print $2}' )
	# Process the status.
	if [ "$packageStatus" == "install" ]; then
		echo "  Package currently installed."
	elif [ "$packageStatus" == "deinstall" ]; then
		echo "  Package marked for deinstallation; attempting to (re)install."
		apt-get install $package
	else
		echo "  Installing."
		apt-get install $package
	fi
done

# Copy all of the files in the bin folder to /usr/local/bin
for f in $( ls bin/ ); do
	# Print label.
	echo "Checking  script: '$f'"
	# Check if such a file already exists.
	if [[ -f "/usr/local/bin/$f" ]]; then
		# Get the difference between the two files.
		d=$( diff bin/$f /usr/local/bin/$f )
		# If it's not empty, overwrite.
		if [ "$d" != "" ]; then
			# Overwrite the script.
			echo "  Warning: overwriting /usr/local/bin/$f"
			# Copy the file.
			cp -f bin/$f /usr/local/bin/
		fi
	else
		# Notify.
		echo "  Copying script to /usr/local/bin/"
		# Copy the file.
		cp -f bin/$f /usr/local/bin/
	fi
done

